# =============================================================
# stocks.py — AUTO-GENERATED NIFTY 500 STOCK SYMBOLS
# =============================================================
# This file contains the auto-generated list of 500+ stocks
# from the Nifty 500 Index constituents list.
# Generated on: 2026-06-20
# =============================================================

STOCKS = [
    ("360ONE", "360ONE.NS", "360 ONE WAM Ltd.", "NBFC"),
    ("3MINDIA", "3MINDIA.NS", "3M India Ltd.", "Other"),
    ("AADHARHFC", "AADHARHFC.NS", "Aadhar Housing Finance Ltd.", "NBFC"),
    ("AARTIIND", "AARTIIND.NS", "Aarti Industries Ltd.", "Chemical"),
    ("AAVAS", "AAVAS.NS", "Aavas Financiers Ltd.", "NBFC"),
    ("ABB", "ABB.NS", "ABB India Ltd.", "Infra"),
    ("ABBOTINDIA", "ABBOTINDIA.NS", "Abbott India Ltd.", "Pharma"),
    ("ABCAPITAL", "ABCAPITAL.NS", "Aditya Birla Capital Ltd.", "NBFC"),
    ("ABDL", "ABDL.NS", "Allied Blenders and Distillers Ltd.", "Consumer"),
    ("ABFRL", "ABFRL.NS", "Aditya Birla Fashion and Retail Ltd.", "Consumer"),
    ("ABLBL", "ABLBL.NS", "Aditya Birla Lifestyle Brands Ltd.", "Consumer"),
    ("ABREL", "ABREL.NS", "Aditya Birla Real Estate Ltd.", "Realty"),
    ("ABSLAMC", "ABSLAMC.NS", "Aditya Birla Sun Life AMC Ltd.", "NBFC"),
    ("ACC", "ACC.NS", "ACC Ltd.", "Infra"),
    ("ACE", "ACE.NS", "Action Construction Equipment Ltd.", "Infra"),
    ("ACMESOLAR", "ACMESOLAR.NS", "ACME Solar Holdings Ltd.", "Power"),
    ("ACUTAAS", "ACUTAAS.NS", "Acutaas Chemicals Ltd.", "Pharma"),
    ("ADANIENSOL", "ADANIENSOL.NS", "Adani Energy Solutions Ltd.", "Power"),
    ("ADANIENT", "ADANIENT.NS", "Adani Enterprises Ltd.", "Metal"),
    ("ADANIGREEN", "ADANIGREEN.NS", "Adani Green Energy Ltd.", "Power"),
    ("ADANIPORTS", "ADANIPORTS.NS", "Adani Ports and Special Economic Zone Ltd.", "Other"),
    ("ADANIPOWER", "ADANIPOWER.NS", "Adani Power Ltd.", "Power"),
    ("AEGISLOG", "AEGISLOG.NS", "Aegis Logistics Ltd.", "Power"),
    ("AEGISVOPAK", "AEGISVOPAK.NS", "Aegis Vopak Terminals Ltd.", "Power"),
    ("AFCONS", "AFCONS.NS", "Afcons Infrastructure Ltd.", "Infra"),
    ("AFFLE", "AFFLE.NS", "Affle 3i Ltd.", "IT"),
    ("AIAENG", "AIAENG.NS", "AIA Engineering Ltd.", "Infra"),
    ("AIIL", "AIIL.NS", "Authum Investment & Infrastructure Ltd.", "NBFC"),
    ("AJANTPHARM", "AJANTPHARM.NS", "Ajanta Pharmaceuticals Ltd.", "Pharma"),
    ("ALKEM", "ALKEM.NS", "Alkem Laboratories Ltd.", "Pharma"),
    ("AMBER", "AMBER.NS", "Amber Enterprises India Ltd.", "Consumer"),
    ("AMBUJACEM", "AMBUJACEM.NS", "Ambuja Cements Ltd.", "Infra"),
    ("ANANDRATHI", "ANANDRATHI.NS", "Anand Rathi Wealth Ltd.", "NBFC"),
    ("ANANTRAJ", "ANANTRAJ.NS", "Anant Raj Ltd.", "Realty"),
    ("ANGELONE", "ANGELONE.NS", "Angel One Ltd.", "NBFC"),
    ("ANTHEM", "ANTHEM.NS", "Anthem Biosciences Ltd.", "Pharma"),
    ("ANURAS", "ANURAS.NS", "Anupam Rasayan India Ltd.", "Chemical"),
    ("APARINDS", "APARINDS.NS", "Apar Industries Ltd.", "Infra"),
    ("APLAPOLLO", "APLAPOLLO.NS", "APL Apollo Tubes Ltd.", "Infra"),
    ("APOLLOHOSP", "APOLLOHOSP.NS", "Apollo Hospitals Enterprise Ltd.", "Pharma"),
    ("APOLLOTYRE", "APOLLOTYRE.NS", "Apollo Tyres Ltd.", "Auto"),
    ("APTUS", "APTUS.NS", "Aptus Value Housing Finance India Ltd.", "NBFC"),
    ("ARE&M", "ARE&M.NS", "Amara Raja Energy & Mobility Ltd.", "Auto"),
    ("ASAHIINDIA", "ASAHIINDIA.NS", "Asahi India Glass Ltd.", "Auto"),
    ("ASHOKLEY", "ASHOKLEY.NS", "Ashok Leyland Ltd.", "Infra"),
    ("ASIANPAINT", "ASIANPAINT.NS", "Asian Paints Ltd.", "Consumer"),
    ("ASTERDM", "ASTERDM.NS", "Aster DM Healthcare Ltd.", "Pharma"),
    ("ASTRAL", "ASTRAL.NS", "Astral Ltd.", "Infra"),
    ("ATGL", "ATGL.NS", "Adani Total Gas Ltd.", "Power"),
    ("ATHERENERG", "ATHERENERG.NS", "Ather Energy Ltd.", "Auto"),
    ("ATUL", "ATUL.NS", "Atul Ltd.", "Chemical"),
    ("AUBANK", "AUBANK.NS", "AU Small Finance Bank Ltd.", "Banking"),
    ("AUROPHARMA", "AUROPHARMA.NS", "Aurobindo Pharma Ltd.", "Pharma"),
    ("AWL", "AWL.NS", "AWL Agri Business Ltd.", "Consumer"),
    ("AXISBANK", "AXISBANK.NS", "Axis Bank Ltd.", "Banking"),
    ("BAJAJ-AUTO", "BAJAJ-AUTO.NS", "Bajaj Auto Ltd.", "Auto"),
    ("BAJAJFINSV", "BAJAJFINSV.NS", "Bajaj Finserv Ltd.", "NBFC"),
    ("BAJAJHFL", "BAJAJHFL.NS", "Bajaj Housing Finance Ltd.", "NBFC"),
    ("BAJAJHLDNG", "BAJAJHLDNG.NS", "Bajaj Holdings & Investment Ltd.", "NBFC"),
    ("BAJFINANCE", "BAJFINANCE.NS", "Bajaj Finance Ltd.", "NBFC"),
    ("BALKRISIND", "BALKRISIND.NS", "Balkrishna Industries Ltd.", "Auto"),
    ("BALRAMCHIN", "BALRAMCHIN.NS", "Balrampur Chini Mills Ltd.", "Consumer"),
    ("BANDHANBNK", "BANDHANBNK.NS", "Bandhan Bank Ltd.", "Banking"),
    ("BANKBARODA", "BANKBARODA.NS", "Bank of Baroda", "Banking"),
    ("BANKINDIA", "BANKINDIA.NS", "Bank of India", "Banking"),
    ("BATAINDIA", "BATAINDIA.NS", "Bata India Ltd.", "Consumer"),
    ("BAYERCROP", "BAYERCROP.NS", "Bayer Cropscience Ltd.", "Chemical"),
    ("BBTC", "BBTC.NS", "Bombay Burmah Trading Corporation Ltd.", "Consumer"),
    ("BDL", "BDL.NS", "Bharat Dynamics Ltd.", "Defence"),
    ("BEL", "BEL.NS", "Bharat Electronics Ltd.", "Defence"),
    ("BELRISE", "BELRISE.NS", "Belrise Industries Ltd.", "Auto"),
    ("BEML", "BEML.NS", "BEML Ltd.", "Infra"),
    ("BERGEPAINT", "BERGEPAINT.NS", "Berger Paints India Ltd.", "Consumer"),
    ("BHARATFORG", "BHARATFORG.NS", "Bharat Forge Ltd.", "Auto"),
    ("BHARTIARTL", "BHARTIARTL.NS", "Bharti Airtel Ltd.", "IT"),
    ("BHARTIHEXA", "BHARTIHEXA.NS", "Bharti Hexacom Ltd.", "IT"),
    ("BHEL", "BHEL.NS", "Bharat Heavy Electricals Ltd.", "Infra"),
    ("BIKAJI", "BIKAJI.NS", "Bikaji Foods International Ltd.", "Consumer"),
    ("BIOCON", "BIOCON.NS", "Biocon Ltd.", "Pharma"),
    ("BLS", "BLS.NS", "BLS International Services Ltd.", "Consumer"),
    ("BLUEDART", "BLUEDART.NS", "Blue Dart Express Ltd.", "Other"),
    ("BLUEJET", "BLUEJET.NS", "Blue Jet Healthcare Ltd.", "Pharma"),
    ("BLUESTARCO", "BLUESTARCO.NS", "Blue Star Ltd.", "Consumer"),
    ("BOSCHLTD", "BOSCHLTD.NS", "Bosch Ltd.", "Auto"),
    ("BPCL", "BPCL.NS", "Bharat Petroleum Corporation Ltd.", "Power"),
    ("BRIGADE", "BRIGADE.NS", "Brigade Enterprises Ltd.", "Realty"),
    ("BRITANNIA", "BRITANNIA.NS", "Britannia Industries Ltd.", "Consumer"),
    ("BSE", "BSE.NS", "BSE Ltd.", "NBFC"),
    ("BSOFT", "BSOFT.NS", "Birlasoft Ltd.", "IT"),
    ("CAMS", "CAMS.NS", "Computer Age Management Services Ltd.", "NBFC"),
    ("CANBK", "CANBK.NS", "Canara Bank", "Banking"),
    ("CANFINHOME", "CANFINHOME.NS", "Can Fin Homes Ltd.", "NBFC"),
    ("CANHLIFE", "CANHLIFE.NS", "Canara HSBC Life Insurance Company Ltd.", "NBFC"),
    ("CAPLIPOINT", "CAPLIPOINT.NS", "Caplin Point Laboratories Ltd.", "Pharma"),
    ("CARBORUNIV", "CARBORUNIV.NS", "Carborundum Universal Ltd.", "Infra"),
    ("CARTRADE", "CARTRADE.NS", "Cartrade Tech Ltd.", "Consumer"),
    ("CASTROLIND", "CASTROLIND.NS", "Castrol India Ltd.", "Power"),
    ("CCL", "CCL.NS", "CCL Products (I) Ltd.", "Consumer"),
    ("CDSL", "CDSL.NS", "Central Depository Services (India) Ltd.", "NBFC"),
    ("CEATLTD", "CEATLTD.NS", "Ceat Ltd.", "Auto"),
    ("CEMPRO", "CEMPRO.NS", "Cemindia Projects Ltd.", "Infra"),
    ("CENTRALBK", "CENTRALBK.NS", "Central Bank of India", "Banking"),
    ("CESC", "CESC.NS", "CESC Ltd.", "Power"),
    ("CGCL", "CGCL.NS", "Capri Global Capital Ltd.", "NBFC"),
    ("CGPOWER", "CGPOWER.NS", "CG Power and Industrial Solutions Ltd.", "Infra"),
    ("CHALET", "CHALET.NS", "Chalet Hotels Ltd.", "Consumer"),
    ("CHAMBLFERT", "CHAMBLFERT.NS", "Chambal Fertilizers & Chemicals Ltd.", "Chemical"),
    ("CHENNPETRO", "CHENNPETRO.NS", "Chennai Petroleum Corporation Ltd.", "Power"),
    ("CHOICEIN", "CHOICEIN.NS", "Choice International Ltd.", "NBFC"),
    ("CHOLAFIN", "CHOLAFIN.NS", "Cholamandalam Investment and Finance Company Ltd.", "NBFC"),
    ("CHOLAHLDNG", "CHOLAHLDNG.NS", "Cholamandalam Financial Holdings Ltd.", "NBFC"),
    ("CIEINDIA", "CIEINDIA.NS", "CIE Automotive India Ltd.", "Auto"),
    ("CIPLA", "CIPLA.NS", "Cipla Ltd.", "Pharma"),
    ("CLEAN", "CLEAN.NS", "Clean Science and Technology Ltd.", "Chemical"),
    ("COALINDIA", "COALINDIA.NS", "Coal India Ltd.", "Power"),
    ("COCHINSHIP", "COCHINSHIP.NS", "Cochin Shipyard Ltd.", "Defence"),
    ("COFORGE", "COFORGE.NS", "Coforge Ltd.", "IT"),
    ("COHANCE", "COHANCE.NS", "Cohance Lifesciences Ltd.", "Pharma"),
    ("COLPAL", "COLPAL.NS", "Colgate Palmolive (India) Ltd.", "Consumer"),
    ("CONCOR", "CONCOR.NS", "Container Corporation of India Ltd.", "Other"),
    ("CONCORDBIO", "CONCORDBIO.NS", "Concord Biotech Ltd.", "Pharma"),
    ("COROMANDEL", "COROMANDEL.NS", "Coromandel International Ltd.", "Chemical"),
    ("CPPLUS", "CPPLUS.NS", "Aditya Infotech Ltd.", "Infra"),
    ("CRAFTSMAN", "CRAFTSMAN.NS", "Craftsman Automation Ltd.", "Auto"),
    ("CREDITACC", "CREDITACC.NS", "CreditAccess Grameen Ltd.", "NBFC"),
    ("CRISIL", "CRISIL.NS", "CRISIL Ltd.", "NBFC"),
    ("CROMPTON", "CROMPTON.NS", "Crompton Greaves Consumer Electricals Ltd.", "Consumer"),
    ("CUB", "CUB.NS", "City Union Bank Ltd.", "NBFC"),
    ("CUMMINSIND", "CUMMINSIND.NS", "Cummins India Ltd.", "Infra"),
    ("CYIENT", "CYIENT.NS", "Cyient Ltd.", "IT"),
    ("DABUR", "DABUR.NS", "Dabur India Ltd.", "Consumer"),
    ("DALBHARAT", "DALBHARAT.NS", "Dalmia Bharat Ltd.", "Infra"),
    ("DATAPATTNS", "DATAPATTNS.NS", "Data Patterns (India) Ltd.", "Defence"),
    ("DCMSHRIRAM", "DCMSHRIRAM.NS", "DCM Shriram Ltd.", "Other"),
    ("DEEPAKFERT", "DEEPAKFERT.NS", "Deepak Fertilisers & Petrochemicals Corp. Ltd.", "Chemical"),
    ("DEEPAKNTR", "DEEPAKNTR.NS", "Deepak Nitrite Ltd.", "Chemical"),
    ("DELHIVERY", "DELHIVERY.NS", "Delhivery Ltd.", "Other"),
    ("DEVYANI", "DEVYANI.NS", "Devyani International Ltd.", "Consumer"),
    ("DIVISLAB", "DIVISLAB.NS", "Divi's Laboratories Ltd.", "Pharma"),
    ("DIXON", "DIXON.NS", "Dixon Technologies (India) Ltd.", "Consumer"),
    ("DLF", "DLF.NS", "DLF Ltd.", "Realty"),
    ("DMART", "DMART.NS", "Avenue Supermarts Ltd.", "Consumer"),
    ("DOMS", "DOMS.NS", "DOMS Industries Ltd.", "Consumer"),
    ("DRREDDY", "DRREDDY.NS", "Dr. Reddy's Laboratories Ltd.", "Pharma"),
    ("ECLERX", "ECLERX.NS", "eClerx Services Ltd.", "Other"),
    ("EICHERMOT", "EICHERMOT.NS", "Eicher Motors Ltd.", "Auto"),
    ("EIDPARRY", "EIDPARRY.NS", "E.I.D. Parry (India) Ltd.", "Consumer"),
    ("EIHOTEL", "EIHOTEL.NS", "EIH Ltd.", "Consumer"),
    ("ELECON", "ELECON.NS", "Elecon Engineering Co. Ltd.", "Infra"),
    ("ELGIEQUIP", "ELGIEQUIP.NS", "Elgi Equipments Ltd.", "Infra"),
    ("EMAMILTD", "EMAMILTD.NS", "Emami Ltd.", "Consumer"),
    ("EMCURE", "EMCURE.NS", "Emcure Pharmaceuticals Ltd.", "Pharma"),
    ("EMMVEE", "EMMVEE.NS", "Emmvee Photovoltaic Power Ltd.", "Infra"),
    ("ENDURANCE", "ENDURANCE.NS", "Endurance Technologies Ltd.", "Auto"),
    ("ENGINERSIN", "ENGINERSIN.NS", "Engineers India Ltd.", "Infra"),
    ("ENRIN", "ENRIN.NS", "Siemens Energy India Ltd.", "Infra"),
    ("ERIS", "ERIS.NS", "Eris Lifesciences Ltd.", "Pharma"),
    ("ESCORTS", "ESCORTS.NS", "Escorts Kubota Ltd.", "Infra"),
    ("ETERNAL", "ETERNAL.NS", "Eternal Ltd.", "Consumer"),
    ("EXIDEIND", "EXIDEIND.NS", "Exide Industries Ltd.", "Auto"),
    ("FACT", "FACT.NS", "Fertilisers and Chemicals Travancore Ltd.", "Chemical"),
    ("FEDERALBNK", "FEDERALBNK.NS", "Federal Bank Ltd.", "Banking"),
    ("FINCABLES", "FINCABLES.NS", "Finolex Cables Ltd.", "Infra"),
    ("FIRSTCRY", "FIRSTCRY.NS", "Brainbees Solutions Ltd.", "Consumer"),
    ("FIVESTAR", "FIVESTAR.NS", "Five-Star Business Finance Ltd.", "NBFC"),
    ("FLUOROCHEM", "FLUOROCHEM.NS", "Gujarat Fluorochemicals Ltd.", "Chemical"),
    ("FORCEMOT", "FORCEMOT.NS", "Force Motors Ltd.", "Auto"),
    ("FORTIS", "FORTIS.NS", "Fortis Healthcare Ltd.", "Pharma"),
    ("FSL", "FSL.NS", "Firstsource Solutions Ltd.", "Other"),
    ("GABRIEL", "GABRIEL.NS", "Gabriel India Ltd.", "Auto"),
    ("GAIL", "GAIL.NS", "GAIL (India) Ltd.", "Power"),
    ("GALLANTT", "GALLANTT.NS", "Gallantt Ispat Ltd.", "Infra"),
    ("GESHIP", "GESHIP.NS", "Great Eastern Shipping Co. Ltd.", "Other"),
    ("GICRE", "GICRE.NS", "General Insurance Corporation of India", "NBFC"),
    ("GILLETTE", "GILLETTE.NS", "Gillette India Ltd.", "Consumer"),
    ("GLAND", "GLAND.NS", "Gland Pharma Ltd.", "Pharma"),
    ("GLAXO", "GLAXO.NS", "Glaxosmithkline Pharmaceuticals Ltd.", "Pharma"),
    ("GLENMARK", "GLENMARK.NS", "Glenmark Pharmaceuticals Ltd.", "Pharma"),
    ("GMDCLTD", "GMDCLTD.NS", "Gujarat Mineral Development Corporation Ltd.", "Metal"),
    ("GMRAIRPORT", "GMRAIRPORT.NS", "GMR Airports Ltd.", "Other"),
    ("GODFRYPHLP", "GODFRYPHLP.NS", "Godfrey Phillips India Ltd.", "Consumer"),
    ("GODIGIT", "GODIGIT.NS", "Go Digit General Insurance Ltd.", "NBFC"),
    ("GODREJCP", "GODREJCP.NS", "Godrej Consumer Products Ltd.", "Consumer"),
    ("GODREJIND", "GODREJIND.NS", "Godrej Industries Ltd.", "Other"),
    ("GODREJPROP", "GODREJPROP.NS", "Godrej Properties Ltd.", "Realty"),
    ("GPIL", "GPIL.NS", "Godawari Power & Ispat Ltd.", "Infra"),
    ("GRANULES", "GRANULES.NS", "Granules India Ltd.", "Pharma"),
    ("GRAPHITE", "GRAPHITE.NS", "Graphite India Ltd.", "Infra"),
    ("GRASIM", "GRASIM.NS", "Grasim Industries Ltd.", "Infra"),
    ("GRAVITA", "GRAVITA.NS", "Gravita India Ltd.", "Metal"),
    ("GROWW", "GROWW.NS", "Billionbrains Garage Ventures Ltd.", "NBFC"),
    ("GRSE", "GRSE.NS", "Garden Reach Shipbuilders & Engineers Ltd.", "Defence"),
    ("GVT&D", "GVT&D.NS", "GE Vernova T&D India Ltd.", "Infra"),
    ("HAL", "HAL.NS", "Hindustan Aeronautics Ltd.", "Defence"),
    ("HAVELLS", "HAVELLS.NS", "Havells India Ltd.", "Consumer"),
    ("HBLENGINE", "HBLENGINE.NS", "HBL Engineering Ltd.", "Infra"),
    ("HCLTECH", "HCLTECH.NS", "HCL Technologies Ltd.", "IT"),
    ("HDBFS", "HDBFS.NS", "HDB Financial Services Ltd.", "NBFC"),
    ("HDFCAMC", "HDFCAMC.NS", "HDFC Asset Management Company Ltd.", "NBFC"),
    ("HDFCBANK", "HDFCBANK.NS", "HDFC Bank Ltd.", "Banking"),
    ("HDFCLIFE", "HDFCLIFE.NS", "HDFC Life Insurance Company Ltd.", "NBFC"),
    ("HEG", "HEG.NS", "H.E.G. Ltd.", "Infra"),
    ("HEROMOTOCO", "HEROMOTOCO.NS", "Hero MotoCorp Ltd.", "Auto"),
    ("HEXT", "HEXT.NS", "Hexaware Technologies Ltd.", "IT"),
    ("HFCL", "HFCL.NS", "HFCL Ltd.", "IT"),
    ("HINDALCO", "HINDALCO.NS", "Hindalco Industries Ltd.", "Metal"),
    ("HINDCOPPER", "HINDCOPPER.NS", "Hindustan Copper Ltd.", "Metal"),
    ("HINDPETRO", "HINDPETRO.NS", "Hindustan Petroleum Corporation Ltd.", "Power"),
    ("HINDUNILVR", "HINDUNILVR.NS", "Hindustan Unilever Ltd.", "Consumer"),
    ("HINDZINC", "HINDZINC.NS", "Hindustan Zinc Ltd.", "Metal"),
    ("HOMEFIRST", "HOMEFIRST.NS", "Home First Finance Company India Ltd.", "NBFC"),
    ("HONASA", "HONASA.NS", "Honasa Consumer Ltd.", "Consumer"),
    ("HONAUT", "HONAUT.NS", "Honeywell Automation India Ltd.", "Infra"),
    ("HSCL", "HSCL.NS", "Himadri Speciality Chemical Ltd.", "Chemical"),
    ("HUDCO", "HUDCO.NS", "Housing & Urban Development Corporation Ltd.", "NBFC"),
    ("HYUNDAI", "HYUNDAI.NS", "Hyundai Motor India Ltd.", "Auto"),
    ("ICICIAMC", "ICICIAMC.NS", "ICICI Prudential Asset Management Company Ltd.", "NBFC"),
    ("ICICIBANK", "ICICIBANK.NS", "ICICI Bank Ltd.", "Banking"),
    ("ICICIGI", "ICICIGI.NS", "ICICI Lombard General Insurance Company Ltd.", "NBFC"),
    ("ICICIPRULI", "ICICIPRULI.NS", "ICICI Prudential Life Insurance Company Ltd.", "NBFC"),
    ("IDBI", "IDBI.NS", "IDBI Bank Ltd.", "Banking"),
    ("IDEA", "IDEA.NS", "Vodafone Idea Ltd.", "IT"),
    ("IDFCFIRSTB", "IDFCFIRSTB.NS", "IDFC First Bank Ltd.", "Banking"),
    ("IEX", "IEX.NS", "Indian Energy Exchange Ltd.", "NBFC"),
    ("IFCI", "IFCI.NS", "IFCI Ltd.", "NBFC"),
    ("IGIL", "IGIL.NS", "International Gemological Institute Ltd.", "Other"),
    ("IGL", "IGL.NS", "Indraprastha Gas Ltd.", "Power"),
    ("IIFL", "IIFL.NS", "IIFL Finance Ltd.", "NBFC"),
    ("IKS", "IKS.NS", "Inventurus Knowledge Solutions Ltd.", "IT"),
    ("INDGN", "INDGN.NS", "Indegene Ltd.", "Pharma"),
    ("INDHOTEL", "INDHOTEL.NS", "Indian Hotels Co. Ltd.", "Consumer"),
    ("INDIACEM", "INDIACEM.NS", "India Cements Ltd.", "Infra"),
    ("INDIAMART", "INDIAMART.NS", "Indiamart Intermesh Ltd.", "Consumer"),
    ("INDIANB", "INDIANB.NS", "Indian Bank", "Banking"),
    ("INDIGO", "INDIGO.NS", "InterGlobe Aviation Ltd.", "Other"),
    ("INDUSINDBK", "INDUSINDBK.NS", "IndusInd Bank Ltd.", "Banking"),
    ("INDUSTOWER", "INDUSTOWER.NS", "Indus Towers Ltd.", "IT"),
    ("INFY", "INFY.NS", "Infosys Ltd.", "IT"),
    ("INOXWIND", "INOXWIND.NS", "Inox Wind Ltd.", "Infra"),
    ("INTELLECT", "INTELLECT.NS", "Intellect Design Arena Ltd.", "IT"),
    ("IOB", "IOB.NS", "Indian Overseas Bank", "Banking"),
    ("IOC", "IOC.NS", "Indian Oil Corporation Ltd.", "Power"),
    ("IPCALAB", "IPCALAB.NS", "Ipca Laboratories Ltd.", "Pharma"),
    ("IRB", "IRB.NS", "IRB Infrastructure Developers Ltd.", "Infra"),
    ("IRCON", "IRCON.NS", "IRCON International Ltd.", "Infra"),
    ("IRCTC", "IRCTC.NS", "Indian Railway Catering And Tourism Corporation Ltd.", "Consumer"),
    ("IREDA", "IREDA.NS", "Indian Renewable Energy Development Agency Ltd.", "NBFC"),
    ("IRFC", "IRFC.NS", "Indian Railway Finance Corporation Ltd.", "NBFC"),
    ("ITC", "ITC.NS", "ITC Ltd.", "Consumer"),
    ("ITCHOTELS", "ITCHOTELS.NS", "ITC Hotels Ltd.", "Consumer"),
    ("ITI", "ITI.NS", "ITI Ltd.", "IT"),
    ("J&KBANK", "J&KBANK.NS", "Jammu & Kashmir Bank Ltd.", "Banking"),
    ("JAINREC", "JAINREC.NS", "Jain Resource Recycling Ltd.", "Metal"),
    ("JBCHEPHARM", "JBCHEPHARM.NS", "J.B. Chemicals & Pharmaceuticals Ltd.", "Pharma"),
    ("JBMA", "JBMA.NS", "JBM Auto Ltd.", "Auto"),
    ("JINDALSAW", "JINDALSAW.NS", "Jindal Saw Ltd.", "Infra"),
    ("JINDALSTEL", "JINDALSTEL.NS", "Jindal Steel Ltd.", "Metal"),
    ("JIOFIN", "JIOFIN.NS", "Jio Financial Services Ltd.", "NBFC"),
    ("JKCEMENT", "JKCEMENT.NS", "J.K. Cement Ltd.", "Infra"),
    ("JKTYRE", "JKTYRE.NS", "JK Tyre & Industries Ltd.", "Auto"),
    ("JMFINANCIL", "JMFINANCIL.NS", "JM Financial Ltd.", "NBFC"),
    ("JPPOWER", "JPPOWER.NS", "Jaiprakash Power Ventures Ltd.", "Power"),
    ("JSL", "JSL.NS", "Jindal Stainless Ltd.", "Metal"),
    ("JSWCEMENT", "JSWCEMENT.NS", "JSW Cement Ltd.", "Infra"),
    ("JSWDULUX", "JSWDULUX.NS", "JSW Dulux Ltd.", "Consumer"),
    ("JSWENERGY", "JSWENERGY.NS", "JSW Energy Ltd.", "Power"),
    ("JSWINFRA", "JSWINFRA.NS", "JSW Infrastructure Ltd.", "Other"),
    ("JSWSTEEL", "JSWSTEEL.NS", "JSW Steel Ltd.", "Metal"),
    ("JUBLFOOD", "JUBLFOOD.NS", "Jubilant Foodworks Ltd.", "Consumer"),
    ("JUBLINGREA", "JUBLINGREA.NS", "Jubilant Ingrevia Ltd.", "Chemical"),
    ("JUBLPHARMA", "JUBLPHARMA.NS", "Jubilant Pharmova Ltd.", "Pharma"),
    ("JWL", "JWL.NS", "Jupiter Wagons Ltd.", "Infra"),
    ("JYOTICNC", "JYOTICNC.NS", "Jyoti CNC Automation Ltd.", "Infra"),
    ("KAJARIACER", "KAJARIACER.NS", "Kajaria Ceramics Ltd.", "Consumer"),
    ("KALYANKJIL", "KALYANKJIL.NS", "Kalyan Jewellers India Ltd.", "Consumer"),
    ("KARURVYSYA", "KARURVYSYA.NS", "Karur Vysya Bank Ltd.", "Banking"),
    ("KAYNES", "KAYNES.NS", "Kaynes Technology India Ltd.", "Infra"),
    ("KEC", "KEC.NS", "Kec International Ltd.", "Infra"),
    ("KEI", "KEI.NS", "KEI Industries Ltd.", "Infra"),
    ("KFINTECH", "KFINTECH.NS", "Kfin Technologies Ltd.", "NBFC"),
    ("KIMS", "KIMS.NS", "Krishna Institute of Medical Sciences Ltd.", "Pharma"),
    ("KIRLOSENG", "KIRLOSENG.NS", "Kirloskar Oil Eng Ltd.", "Infra"),
    ("KOTAKBANK", "KOTAKBANK.NS", "Kotak Mahindra Bank Ltd.", "Banking"),
    ("KPIL", "KPIL.NS", "Kalpataru Projects International Ltd.", "Infra"),
    ("KPITTECH", "KPITTECH.NS", "KPIT Technologies Ltd.", "IT"),
    ("KPRMILL", "KPRMILL.NS", "K.P.R. Mill Ltd.", "Consumer"),
    ("LALPATHLAB", "LALPATHLAB.NS", "Dr. Lal Path Labs Ltd.", "Pharma"),
    ("LATENTVIEW", "LATENTVIEW.NS", "Latent View Analytics Ltd.", "IT"),
    ("LAURUSLABS", "LAURUSLABS.NS", "Laurus Labs Ltd.", "Pharma"),
    ("LEMONTREE", "LEMONTREE.NS", "Lemon Tree Hotels Ltd.", "Consumer"),
    ("LENSKART", "LENSKART.NS", "Lenskart Solutions Ltd.", "Consumer"),
    ("LGEINDIA", "LGEINDIA.NS", "LG Electronics India Ltd.", "Consumer"),
    ("LICHSGFIN", "LICHSGFIN.NS", "LIC Housing Finance Ltd.", "NBFC"),
    ("LICI", "LICI.NS", "Life Insurance Corporation of India", "NBFC"),
    ("LINDEINDIA", "LINDEINDIA.NS", "Linde India Ltd.", "Chemical"),
    ("LLOYDSME", "LLOYDSME.NS", "Lloyds Metals And Energy Ltd.", "Metal"),
    ("LODHA", "LODHA.NS", "Lodha Developers Ltd.", "Realty"),
    ("LT", "LT.NS", "Larsen & Toubro Ltd.", "Infra"),
    ("LTF", "LTF.NS", "L&T Finance Ltd.", "NBFC"),
    ("LTFOODS", "LTFOODS.NS", "LT Foods Ltd.", "Consumer"),
    ("LTM", "LTM.NS", "LTM Ltd.", "IT"),
    ("LTTS", "LTTS.NS", "L&T Technology Services Ltd.", "IT"),
    ("LUPIN", "LUPIN.NS", "Lupin Ltd.", "Pharma"),
    ("M&M", "M&M.NS", "Mahindra & Mahindra Ltd.", "Auto"),
    ("M&MFIN", "M&MFIN.NS", "Mahindra & Mahindra Financial Services Ltd.", "NBFC"),
    ("MAHABANK", "MAHABANK.NS", "Bank of Maharashtra", "Banking"),
    ("MANAPPURAM", "MANAPPURAM.NS", "Manappuram Finance Ltd.", "NBFC"),
    ("MANKIND", "MANKIND.NS", "Mankind Pharma Ltd.", "Pharma"),
    ("MAPMYINDIA", "MAPMYINDIA.NS", "C.E. Info Systems Ltd.", "IT"),
    ("MARICO", "MARICO.NS", "Marico Ltd.", "Consumer"),
    ("MARUTI", "MARUTI.NS", "Maruti Suzuki India Ltd.", "Auto"),
    ("MAXHEALTH", "MAXHEALTH.NS", "Max Healthcare Institute Ltd.", "Pharma"),
    ("MAZDOCK", "MAZDOCK.NS", "Mazagoan Dock Shipbuilders Ltd.", "Defence"),
    ("MCX", "MCX.NS", "Multi Commodity Exchange of India Ltd.", "NBFC"),
    ("MEDANTA", "MEDANTA.NS", "Global Health Ltd.", "Pharma"),
    ("MEESHO", "MEESHO.NS", "Meesho Ltd.", "Consumer"),
    ("MFSL", "MFSL.NS", "Max Financial Services Ltd.", "NBFC"),
    ("MGL", "MGL.NS", "Mahanagar Gas Ltd.", "Power"),
    ("MINDACORP", "MINDACORP.NS", "Minda Corporation Ltd.", "Auto"),
    ("MMTC", "MMTC.NS", "MMTC Ltd.", "Other"),
    ("MOTHERSON", "MOTHERSON.NS", "Samvardhana Motherson International Ltd.", "Auto"),
    ("MOTILALOFS", "MOTILALOFS.NS", "Motilal Oswal Financial Services Ltd.", "NBFC"),
    ("MPHASIS", "MPHASIS.NS", "MphasiS Ltd.", "IT"),
    ("MRF", "MRF.NS", "MRF Ltd.", "Auto"),
    ("MRPL", "MRPL.NS", "Mangalore Refinery & Petrochemicals Ltd.", "Power"),
    ("MSUMI", "MSUMI.NS", "Motherson Sumi Wiring India Ltd.", "Auto"),
    ("MUTHOOTFIN", "MUTHOOTFIN.NS", "Muthoot Finance Ltd.", "NBFC"),
    ("NAM-INDIA", "NAM-INDIA.NS", "Nippon Life India Asset Management Ltd.", "NBFC"),
    ("NATCOPHARM", "NATCOPHARM.NS", "NATCO Pharma Ltd.", "Pharma"),
    ("NATIONALUM", "NATIONALUM.NS", "National Aluminium Co. Ltd.", "Metal"),
    ("NAUKRI", "NAUKRI.NS", "Info Edge (India) Ltd.", "Consumer"),
    ("NAVA", "NAVA.NS", "Nava Ltd.", "Power"),
    ("NAVINFLUOR", "NAVINFLUOR.NS", "Navin Fluorine International Ltd.", "Chemical"),
    ("NBCC", "NBCC.NS", "NBCC (India) Ltd.", "Infra"),
    ("NCC", "NCC.NS", "NCC Ltd.", "Infra"),
    ("NESTLEIND", "NESTLEIND.NS", "Nestle India Ltd.", "Consumer"),
    ("NETWEB", "NETWEB.NS", "Netweb Technologies India Ltd.", "IT"),
    ("NEULANDLAB", "NEULANDLAB.NS", "Neuland Laboratories Ltd.", "Pharma"),
    ("NEWGEN", "NEWGEN.NS", "Newgen Software Technologies Ltd.", "IT"),
    ("NH", "NH.NS", "Narayana Hrudayalaya Ltd.", "Pharma"),
    ("NHPC", "NHPC.NS", "NHPC Ltd.", "Power"),
    ("NIACL", "NIACL.NS", "The New India Assurance Company Ltd.", "NBFC"),
    ("NIVABUPA", "NIVABUPA.NS", "Niva Bupa Health Insurance Company Ltd.", "NBFC"),
    ("NLCINDIA", "NLCINDIA.NS", "NLC India Ltd.", "Power"),
    ("NMDC", "NMDC.NS", "NMDC Ltd.", "Metal"),
    ("NSLNISP", "NSLNISP.NS", "NMDC Steel Ltd.", "Metal"),
    ("NTPC", "NTPC.NS", "NTPC Ltd.", "Power"),
    ("NTPCGREEN", "NTPCGREEN.NS", "NTPC Green Energy Ltd.", "Power"),
    ("NUVAMA", "NUVAMA.NS", "Nuvama Wealth Management Ltd.", "NBFC"),
    ("NUVOCO", "NUVOCO.NS", "Nuvoco Vistas Corporation Ltd.", "Infra"),
    ("NYKAA", "NYKAA.NS", "FSN E-Commerce Ventures Ltd.", "Consumer"),
    ("OBEROIRLTY", "OBEROIRLTY.NS", "Oberoi Realty Ltd.", "Realty"),
    ("OFSS", "OFSS.NS", "Oracle Financial Services Software Ltd.", "IT"),
    ("OIL", "OIL.NS", "Oil India Ltd.", "Power"),
    ("OLAELEC", "OLAELEC.NS", "Ola Electric Mobility Ltd.", "Auto"),
    ("OLECTRA", "OLECTRA.NS", "Olectra Greentech Ltd.", "Auto"),
    ("ONESOURCE", "ONESOURCE.NS", "Onesource Specialty Pharma Ltd.", "Pharma"),
    ("ONGC", "ONGC.NS", "Oil & Natural Gas Corporation Ltd.", "Power"),
    ("PAGEIND", "PAGEIND.NS", "Page Industries Ltd.", "Consumer"),
    ("PARADEEP", "PARADEEP.NS", "Paradeep Phosphates Ltd.", "Chemical"),
    ("PATANJALI", "PATANJALI.NS", "Patanjali Foods Ltd.", "Consumer"),
    ("PAYTM", "PAYTM.NS", "One 97 Communications Ltd.", "NBFC"),
    ("PCBL", "PCBL.NS", "PCBL Chemical Ltd.", "Chemical"),
    ("PERSISTENT", "PERSISTENT.NS", "Persistent Systems Ltd.", "IT"),
    ("PETRONET", "PETRONET.NS", "Petronet LNG Ltd.", "Power"),
    ("PFC", "PFC.NS", "Power Finance Corporation Ltd.", "NBFC"),
    ("PFIZER", "PFIZER.NS", "Pfizer Ltd.", "Pharma"),
    ("PGEL", "PGEL.NS", "PG Electroplast Ltd.", "Consumer"),
    ("PHOENIXLTD", "PHOENIXLTD.NS", "Phoenix Mills Ltd.", "Realty"),
    ("PIDILITIND", "PIDILITIND.NS", "Pidilite Industries Ltd.", "Chemical"),
    ("PIIND", "PIIND.NS", "PI Industries Ltd.", "Chemical"),
    ("PINELABS", "PINELABS.NS", "Pine Labs Ltd.", "NBFC"),
    ("PIRAMALFIN", "PIRAMALFIN.NS", "Piramal Finance Ltd.", "NBFC"),
    ("PNB", "PNB.NS", "Punjab National Bank", "Banking"),
    ("PNBHOUSING", "PNBHOUSING.NS", "PNB Housing Finance Ltd.", "NBFC"),
    ("POLICYBZR", "POLICYBZR.NS", "PB Fintech Ltd.", "NBFC"),
    ("POLYCAB", "POLYCAB.NS", "Polycab India Ltd.", "Infra"),
    ("POLYMED", "POLYMED.NS", "Poly Medicure Ltd.", "Pharma"),
    ("POONAWALLA", "POONAWALLA.NS", "Poonawalla Fincorp Ltd.", "NBFC"),
    ("POWERGRID", "POWERGRID.NS", "Power Grid Corporation of India Ltd.", "Power"),
    ("POWERINDIA", "POWERINDIA.NS", "Hitachi Energy India Ltd.", "Infra"),
    ("PPLPHARMA", "PPLPHARMA.NS", "Piramal Pharma Ltd.", "Pharma"),
    ("PREMIERENE", "PREMIERENE.NS", "Premier Energies Ltd.", "Infra"),
    ("PRESTIGE", "PRESTIGE.NS", "Prestige Estates Projects Ltd.", "Realty"),
    ("PTCIL", "PTCIL.NS", "PTC Industries Ltd.", "Infra"),
    ("PVRINOX", "PVRINOX.NS", "PVR INOX Ltd.", "Consumer"),
    ("PWL", "PWL.NS", "Physicswallah Ltd.", "Consumer"),
    ("RADICO", "RADICO.NS", "Radico Khaitan Ltd", "Consumer"),
    ("RAILTEL", "RAILTEL.NS", "Railtel Corporation Of India Ltd.", "IT"),
    ("RAINBOW", "RAINBOW.NS", "Rainbow Childrens Medicare Ltd.", "Pharma"),
    ("RAMCOCEM", "RAMCOCEM.NS", "The Ramco Cements Ltd.", "Infra"),
    ("RBLBANK", "RBLBANK.NS", "RBL Bank Ltd.", "NBFC"),
    ("RECLTD", "RECLTD.NS", "REC Ltd.", "NBFC"),
    ("REDINGTON", "REDINGTON.NS", "Redington Ltd.", "Other"),
    ("RELIANCE", "RELIANCE.NS", "Reliance Industries Ltd.", "Power"),
    ("RHIM", "RHIM.NS", "RHI MAGNESITA INDIA LTD.", "Infra"),
    ("RITES", "RITES.NS", "RITES Ltd.", "Infra"),
    ("RKFORGE", "RKFORGE.NS", "Ramkrishna Forgings Ltd.", "Auto"),
    ("RPOWER", "RPOWER.NS", "Reliance Power Ltd.", "Power"),
    ("RRKABEL", "RRKABEL.NS", "R R Kabel Ltd.", "Infra"),
    ("RVNL", "RVNL.NS", "Rail Vikas Nigam Ltd.", "Infra"),
    ("SAGILITY", "SAGILITY.NS", "Sagility Ltd.", "IT"),
    ("SAIL", "SAIL.NS", "Steel Authority of India Ltd.", "Metal"),
    ("SAILIFE", "SAILIFE.NS", "Sai Life Sciences Ltd.", "Pharma"),
    ("SAMMAANCAP", "SAMMAANCAP.NS", "Sammaan Capital Ltd.", "NBFC"),
    ("SAPPHIRE", "SAPPHIRE.NS", "Sapphire Foods India Ltd.", "Consumer"),
    ("SARDAEN", "SARDAEN.NS", "Sarda Energy and Minerals Ltd.", "Metal"),
    ("SAREGAMA", "SAREGAMA.NS", "Saregama India Ltd", "Consumer"),
    ("SBFC", "SBFC.NS", "SBFC Finance Ltd.", "NBFC"),
    ("SBICARD", "SBICARD.NS", "SBI Cards and Payment Services Ltd.", "NBFC"),
    ("SBILIFE", "SBILIFE.NS", "SBI Life Insurance Company Ltd.", "NBFC"),
    ("SBIN", "SBIN.NS", "State Bank of India", "Banking"),
    ("SCHAEFFLER", "SCHAEFFLER.NS", "Schaeffler India Ltd.", "Auto"),
    ("SCHNEIDER", "SCHNEIDER.NS", "Schneider Electric Infrastructure Ltd.", "Infra"),
    ("SCI", "SCI.NS", "Shipping Corporation of India Ltd.", "Other"),
    ("SHREECEM", "SHREECEM.NS", "Shree Cement Ltd.", "Infra"),
    ("SHRIRAMFIN", "SHRIRAMFIN.NS", "Shriram Finance Ltd.", "NBFC"),
    ("SHYAMMETL", "SHYAMMETL.NS", "Shyam Metalics and Energy Ltd.", "Infra"),
    ("SIEMENS", "SIEMENS.NS", "Siemens Ltd.", "Infra"),
    ("SIGNATURE", "SIGNATURE.NS", "Signatureglobal (India) Ltd.", "Realty"),
    ("SJVN", "SJVN.NS", "SJVN Ltd.", "Power"),
    ("SOBHA", "SOBHA.NS", "Sobha Ltd.", "Realty"),
    ("SOLARINDS", "SOLARINDS.NS", "Solar Industries India Ltd.", "Chemical"),
    ("SONACOMS", "SONACOMS.NS", "Sona BLW Precision Forgings Ltd.", "Auto"),
    ("SONATSOFTW", "SONATSOFTW.NS", "Sonata Software Ltd.", "IT"),
    ("SPLPETRO", "SPLPETRO.NS", "Supreme Petrochem Ltd.", "Chemical"),
    ("SRF", "SRF.NS", "SRF Ltd.", "Chemical"),
    ("STARHEALTH", "STARHEALTH.NS", "Star Health and Allied Insurance Company Ltd.", "NBFC"),
    ("SUMICHEM", "SUMICHEM.NS", "Sumitomo Chemical India Ltd.", "Chemical"),
    ("SUNDARMFIN", "SUNDARMFIN.NS", "Sundaram Finance Ltd.", "NBFC"),
    ("SUNPHARMA", "SUNPHARMA.NS", "Sun Pharmaceutical Industries Ltd.", "Pharma"),
    ("SUNTV", "SUNTV.NS", "Sun TV Network Ltd.", "Consumer"),
    ("SUPREMEIND", "SUPREMEIND.NS", "Supreme Industries Ltd.", "Infra"),
    ("SUZLON", "SUZLON.NS", "Suzlon Energy Ltd.", "Infra"),
    ("SWANCORP", "SWANCORP.NS", "Swan Corp Ltd.", "Chemical"),
    ("SWIGGY", "SWIGGY.NS", "Swiggy Ltd.", "Consumer"),
    ("SYNGENE", "SYNGENE.NS", "Syngene International Ltd.", "Pharma"),
    ("SYRMA", "SYRMA.NS", "Syrma SGS Technology Ltd.", "Infra"),
    ("TARIL", "TARIL.NS", "Transformers And Rectifiers (India) Ltd.", "Infra"),
    ("TATACAP", "TATACAP.NS", "Tata Capital Ltd.", "NBFC"),
    ("TATACHEM", "TATACHEM.NS", "Tata Chemicals Ltd.", "Chemical"),
    ("TATACOMM", "TATACOMM.NS", "Tata Communications Ltd.", "IT"),
    ("TATACONSUM", "TATACONSUM.NS", "Tata Consumer Products Ltd.", "Consumer"),
    ("TATAELXSI", "TATAELXSI.NS", "Tata Elxsi Ltd.", "IT"),
    ("TATAINVEST", "TATAINVEST.NS", "Tata Investment Corporation Ltd.", "NBFC"),
    ("TATAPOWER", "TATAPOWER.NS", "Tata Power Co. Ltd.", "Power"),
    ("TATASTEEL", "TATASTEEL.NS", "Tata Steel Ltd.", "Metal"),
    ("TATATECH", "TATATECH.NS", "Tata Technologies Ltd.", "IT"),
    ("TBOTEK", "TBOTEK.NS", "TBO Tek Ltd.", "Consumer"),
    ("TCS", "TCS.NS", "Tata Consultancy Services Ltd.", "IT"),
    ("TECHM", "TECHM.NS", "Tech Mahindra Ltd.", "IT"),
    ("TECHNOE", "TECHNOE.NS", "Techno Electric & Engineering Company Ltd.", "Infra"),
    ("TEGA", "TEGA.NS", "Tega Industries Ltd.", "Infra"),
    ("TEJASNET", "TEJASNET.NS", "Tejas Networks Ltd.", "IT"),
    ("TENNIND", "TENNIND.NS", "Tenneco Clean Air India Ltd.", "Auto"),
    ("THELEELA", "THELEELA.NS", "Leela Palaces Hotels & Resorts Ltd.", "Consumer"),
    ("THERMAX", "THERMAX.NS", "Thermax Ltd.", "Infra"),
    ("TIINDIA", "TIINDIA.NS", "Tube Investments of India Ltd.", "Auto"),
    ("TIMKEN", "TIMKEN.NS", "Timken India Ltd.", "Infra"),
    ("TITAGARH", "TITAGARH.NS", "Titagarh Rail Systems Ltd.", "Infra"),
    ("TITAN", "TITAN.NS", "Titan Company Ltd.", "Consumer"),
    ("TMCV", "TMCV.NS", "Tata Motors Ltd.", "Infra"),
    ("TMPV", "TMPV.NS", "Tata Motors Passenger Vehicles Ltd.", "Auto"),
    ("TORNTPHARM", "TORNTPHARM.NS", "Torrent Pharmaceuticals Ltd.", "Pharma"),
    ("TORNTPOWER", "TORNTPOWER.NS", "Torrent Power Ltd.", "Power"),
    ("TRAVELFOOD", "TRAVELFOOD.NS", "Travel Food Services Ltd.", "Consumer"),
    ("TRENT", "TRENT.NS", "Trent Ltd.", "Consumer"),
    ("TRIDENT", "TRIDENT.NS", "Trident Ltd.", "Consumer"),
    ("TRITURBINE", "TRITURBINE.NS", "Triveni Turbine Ltd.", "Infra"),
    ("TTML", "TTML.NS", "Tata Teleservices (Maharashtra) Ltd.", "IT"),
    ("TVSMOTOR", "TVSMOTOR.NS", "TVS Motor Company Ltd.", "Auto"),
    ("UBL", "UBL.NS", "United Breweries Ltd.", "Consumer"),
    ("UCOBANK", "UCOBANK.NS", "UCO Bank", "Banking"),
    ("ULTRACEMCO", "ULTRACEMCO.NS", "UltraTech Cement Ltd.", "Infra"),
    ("UNIONBANK", "UNIONBANK.NS", "Union Bank of India", "Banking"),
    ("UNITDSPR", "UNITDSPR.NS", "United Spirits Ltd.", "Consumer"),
    ("UNOMINDA", "UNOMINDA.NS", "UNO Minda Ltd.", "Auto"),
    ("UPL", "UPL.NS", "UPL Ltd.", "Chemical"),
    ("URBANCO", "URBANCO.NS", "Urban Company Ltd.", "Consumer"),
    ("USHAMART", "USHAMART.NS", "Usha Martin Ltd.", "Infra"),
    ("UTIAMC", "UTIAMC.NS", "UTI Asset Management Company Ltd.", "NBFC"),
    ("VAML", "VAML.NS", "Vedanta Aluminium Metal Ltd.", "Metal"),
    ("VBL", "VBL.NS", "Varun Beverages Ltd.", "Consumer"),
    ("VEDL", "VEDL.NS", "Vedanta Ltd.", "Metal"),
    ("VIJAYA", "VIJAYA.NS", "Vijaya Diagnostic Centre Ltd.", "Pharma"),
    ("VMM", "VMM.NS", "Vishal Mega Mart Ltd.", "Consumer"),
    ("VOGL", "VOGL.NS", "Vedanta Oil and Gas Ltd.", "Power"),
    ("VOLTAS", "VOLTAS.NS", "Voltas Ltd.", "Consumer"),
    ("VTL", "VTL.NS", "Vardhman Textiles Ltd.", "Consumer"),
    ("WAAREEENER", "WAAREEENER.NS", "Waaree Energies Ltd.", "Infra"),
    ("WELCORP", "WELCORP.NS", "Welspun Corp Ltd.", "Infra"),
    ("WELSPUNLIV", "WELSPUNLIV.NS", "Welspun Living Ltd.", "Consumer"),
    ("WHIRLPOOL", "WHIRLPOOL.NS", "Whirlpool of India Ltd.", "Consumer"),
    ("WIPRO", "WIPRO.NS", "Wipro Ltd.", "IT"),
    ("WOCKPHARMA", "WOCKPHARMA.NS", "Wockhardt Ltd.", "Pharma"),
    ("YESBANK", "YESBANK.NS", "Yes Bank Ltd.", "Banking"),
    ("ZEEL", "ZEEL.NS", "Zee Entertainment Enterprises Ltd.", "Consumer"),
    ("ZENSARTECH", "ZENSARTECH.NS", "Zensar Technolgies Ltd.", "IT"),
    ("ZENTEC", "ZENTEC.NS", "Zen Technologies Ltd.", "Infra"),
    ("ZFCVINDIA", "ZFCVINDIA.NS", "ZF Commercial Vehicle Control Systems India Ltd.", "Auto"),
    ("ZYDUSLIFE", "ZYDUSLIFE.NS", "Zydus Lifesciences Ltd.", "Pharma"),
    ("ZYDUSWELL", "ZYDUSWELL.NS", "Zydus Wellness Ltd.", "Consumer"),
]

# ── NIFTY 50 INDEX ────────────────────────────────────────────
NIFTY_SYM = "^NSEI"

# ── QUICK STATS ───────────────────────────────────────────────
if __name__ == "__main__":
    from collections import Counter
    sectors = Counter(s[3] for s in STOCKS)
    print(f"Total stocks : {len(STOCKS)}")
    print(f"Sectors      : {len(sectors)}")
    print()
    for sector, count in sorted(sectors.items()):
        names = [s[0] for s in STOCKS if s[3] == sector]
        print(f"  {sector:<12} ({count:>3})  { ', '.join(names[:10]) }...")